---
version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports: 
      - '3000:3000'
  api:
    build: ./api
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db 
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
volumes:
  mysql_data:
...